# Generated by Django 4.2.10 on 2024-03-06 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_answer2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer2',
        ),
    ]
