# Generated by Django 4.2.10 on 2024-03-06 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0003_delete_answer2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer',
            new_name='Answer1',
        ),
        migrations.RenameModel(
            old_name='Question',
            new_name='Question1',
        ),
    ]
