# Generated by Django 4.2.10 on 2024-03-06 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0004_rename_answer_answer1_rename_question_question1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer1',
            new_name='Answer',
        ),
        migrations.RenameModel(
            old_name='Question1',
            new_name='Question',
        ),
    ]
